### ISSUE TITLE
setup-ruby-pkgs

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/setup-ruby-pkgs#1]
@eregon @ioquatix

I've got a start on a package install action.  Works with ruby/openssl & puma, probably check psych next.

Still have more work to do on the Windows side, more inputs, gcc issues with older Rubies, etc.  The gcc issue is actually with older patch/teeny versions. like 2.4.3 or 2.5.2.  If one uses 2.4, 2.5, & 2.6, all is okay.

Being a Windows/MRI type, need help with other platforms/OS's...

I could care less where the repo lives, I just think a 'package' companion to setup-ruby is needed.

**Comment by ioquatix** [comment]
Even if we just get a few standard packages working cross platform, it's a great way for other packages to support testing windows and linux etc.

**Comment by MSP-Greg** [comment]
Does the 'package' concept exist for JRuby or TruffleRuby?  I've run jruby-head locally, but that's about the extent of it...

**Comment by eregon** [comment]
No, there is no `package` for JRuby, TruffleRuby, just as there isn't for MRI.
Ruby has gems, not packages.
Only operating have packages, isn't it?

**Comment by eregon** [comment]
Thank you for starting this :)

**Comment by MSP-Greg** [comment]
> No, there is no package for JRuby, TruffleRuby, just as there isn't for MRI.

Well, until you come up with a better name, we'll use the term packages.  How are brew or pacman normally described?

Anyway, previously I've mentioned that any action like this needs to follow Ruby version selection/installation.

Now that we've got multiple Ruby platforms supported on OS's, that need is a little more clear.

An example would be Puma.  It needs ragel for any MRI Ruby.  But, it also tests JRuby.  So, we can't determine whether to install ragel without knowing whether the job's Ruby is MRI or not.

Also, please consider whether the idea here should be included with setup-ruby.

With this separate, Puma would be:
```yaml
- name: load ruby
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: ${{ matrix.ruby }}

- name: setup compile tools, ragel, openssl
  uses: MSP-Greg/setup-ruby-pkgs@v1
  with:
    apt-get: ragel
    brew: ragel
    mingw: _upgrade_ openssl ragel
```

With this part of sertup-ruby@v2:
```yaml
- name: load ruby & build dependencies
  uses: ruby/setup-ruby@v2
  with:
    ruby-version: ${{ matrix.ruby }}
    apt-get: ragel
    brew: ragel
    mingw: _upgrade_ openssl ragel
```

Personally, I think the 2nd version is much better.  If there are no build dependencies, it is identical to v1...
