### ISSUE TITLE
It should be possible to use this action without running setup-ruby

### ISSUE THREAD

**Issue by eregon** [MSP-Greg/setup-ruby-pkgs#5]
So for instance I can test a given branch/commit of setup-ruby.
```yml
      - uses: eregon/setup-ruby@somebranch
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          apt-get: ragel
          brew: ragel
          mingw: _upgrade_ openssl ragel
```

Currently this fails:
https://github.com/eregon/puma/runs/745365296?check_suite_focus=true
```
Run MSP-Greg/setup-ruby-pkgs@v1
  with:
    apt-get: ragel
    brew: ragel
    mingw: _upgrade_ openssl ragel
    ruby-version: default
    bundler: default
    working-directory: .
  env:
    CI: true
    TESTOPTS: -v
    PATH: /home/runner/.rubies/ruby-2.2.10/bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin
Image info: https://github.com/actions/virtual-environments/tree/ubuntu18/20200518.1/images/linux
  Running ruby/setup-ruby
  pwd: /home/runner/work/puma/puma
##[error]input ruby-version needs to be specified if no .ruby-version or .tool-versions file exists
  took   0.18 s
  Running MSP-Greg/setup-ruby-pkgs 1.12.0
apt-get ragel
  took   7.39 s
```

**Comment by eregon** [comment]
There is actually logic for this:
https://github.com/MSP-Greg/setup-ruby-pkgs/blob/55f53bfc958141703e587affef934b6848eae76d/index.js#L30

But that expects an empty string for Ruby version, and that's not the default value from `action.yml`.

I would have thought just not setting `ruby-version` for this action would be enough to not run `setup-ruby` in this action. But that means the behavior when `ruby-version` is unset (If the ruby-version input is not specified, .ruby-version is tried first, followed by .tool-versions) cannot be used with this action. Thoughts?

**Comment by MSP-Greg** [comment]
I realized this issue earlier, but was working on something else.  Let me switch gears.

I was wondering about testing the location of the enabled/default ruby?  If it has been changed from toolcache, than setup-ruby has run?

Also, maybe I should add an input that specifies what branch/tag is used for setup-ruby?  That might help for our own testing?

**Comment by eregon** [comment]
> I was wondering about testing the location of the enabled/default ruby? If it has been changed from toolcache, than setup-ruby has run?

That's an interesting idea, but it would mean it would also not run if e.g. PATH was changed to include another Ruby. Probably a rare case, but quite confusing then.

Concretely, using `ruby-version: ''` is not so bad, but I'd suggest maybe having another word to not have to care about quoting like `skip`:
```yml
- uses: MSP-Greg/setup-ruby-pkgs@v1
  with:
    ruby-version: skip
    # Or maybe better
    setup-ruby: skip
```
